config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resources :trainings, only: [:index, :show]
  get '/trainings/answers/:id/:answer_id', to: 'trainings#answers', as: 'answer_training'
  resources :learn, only: [:index]
  get '/learn/:category', to: 'learn#index', as: 'category_learn'
  resources :practices, only: [:index, :show]
  get '/practices/answers/:id/:answer_id', to: 'practices#answers', as: 'answer_practice'
  get '/practices/respond/:id/:answer_id', to: 'practices#respond', as: 'respond_practice'

  root 'home#index'

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :authenticate_user!
  before_action :need_training?
  before_action :valid_training?, only: [:show]

  def index
    # Find a valid question for user and redirect to show
    question = current_user.training_question
    redirect_to training_url(question) and return
  end

  def show
    add_breadcrumb "Dashboard", root_path
    add_breadcrumb "Entrenamiento"
  end

  def answers
    redirect_to root_url, alert: "¡Ups! Lo sentimos, la pregunta que intento contestar no existe." and return unless question
    @answer = current_user.user_questions.where(question_id: question.id).first_or_initialize
    if @answer.new_record?
      @answer.question_id = question.id
      @answer.answer = params[:answer_id]
      @answer.level = question.level
      @answer.save
    end
    add_breadcrumb "Dashboard", root_path
    add_breadcrumb "Entrenamiento"
  end

  def question
    @question ||= Question.find(params[:id])
  end
  helper_method :question

  def need_training?
    redirect_to root_url, notice: '¡Felicidades! Completaste satisfactoriamente el entrenamiento' and return unless current_user.need_training?
  end

  def valid_training?
    redirect_to trainings_url and return if current_user.question_ids.include?(question.id)
  end
end

app/views/trainings/answers.haml
%ul.breadcrumb
  = render_breadcrumbs tag: :li, separator: ''
.panel{class: "panel-#{@answer.correct? ? "success" : "danger"}"}
  .panel-heading
    %strong
      %span.glyphicon{aria: {hidden: true}, class: "#{question.glyphicon}"}
      = question.category_s
  .panel-body
    = question.question
    - if question.image.present?
      .row
        .col-sm-offset-5.col-sm-2.col-xs-6.col-xs-offset-3
          = image_tag(question.image.url(:thumb), class: 'img-responsive img-thumbnail')
  .list-group
    - ( 1 .. 4).each do |n|
      - if question["answer_#{n}"].present?
        .list-group-item{class: @answer.correct_answer == n ? 'success' : ( @answer.answer == n ? 'danger' : nil) }
          .row-action-primary
            = link_to 'javascript:void(0)' do
              %i.material-icons
                - if @answer.correct_answer == n
                  check_circle
                - elsif @answer.answer == n
                  error
                - else
                  - case n
                  - when 1
                    looks_one
                  - when 2
                    looks_two
                  - when 3
                    looks_3
                  - else
                    looks_4
          .row-content
            .list-group-item-text
              = link_to 'javascript:void(0)', class: 'btn btn-no-upper' do
                = question["answer_#{n}"]
        - if n < 4
          .list-group-separator
    %div.text-right
      = link_to "Siguiente pregunta", trainings_url, class: 'btn'

= "#{current_user.percent_training}%"
completado
.progress
  .progress-bar{role: 'progressbar', aria: {valuenow: current_user.percent_training, valuemin: 0, valuemax: 100}, style: "width: #{current_user.percent_training == 0 ? "2" : current_user.percent_training}%;", class: "#{current_user.percent_training < 20 ? "progress-bar-danger" : ( current_user.percent_training < 70 ? "progress-bar-warning" : "progress-bar-success" )}"}

app/views/trainings/show.haml
%ul.breadcrumb
  = render_breadcrumbs tag: :li, separator: ''
.panel.panel-default
  .panel-heading
    %strong
      %span.glyphicon{aria: {hidden: true}, class: "#{question.glyphicon}"}
      = question.category_s
  .panel-body
    = question.question
    - if question.image.present?
      .row
        .col-sm-offset-5.col-sm-2.col-xs-6.col-xs-offset-3
          = image_tag(question.image.url(:thumb), class: 'img-responsive img-thumbnail')
  .list-group
    - ( 1 .. 4).each do |n|
      - if question["answer_#{n}"].present?
        .list-group-item
          .row-action-primary
            = link_to answer_training_url(question, n) do
              %i.material-icons
                - case n
                - when 1
                  looks_one
                - when 2
                  looks_two
                - when 3
                  looks_3
                - else
                  looks_4
          .row-content
            .list-group-item-text
              = link_to answer_training_url(question, n), class: 'btn btn-no-upper' do
                = question["answer_#{n}"]
        - if n < 4
          .list-group-separator

= "#{current_user.percent_training}%"
completado
.progress
  .progress-bar{role: 'progressbar', aria: {valuenow: current_user.percent_training, valuemin: 0, valuemax: 100}, style: "width: #{current_user.percent_training == 0 ? "2" : current_user.percent_training}%;", class: "#{current_user.percent_training < 20 ? "progress-bar-danger" : ( current_user.percent_training < 70 ? "progress-bar-warning" : "progress-bar-success" )}"}