config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resources :trainings, only: [:index, :show]
  get '/trainings/answers/:id/:answer_id', to: 'trainings#answers', as: 'answer_training'
  resources :learn, only: [:index]
  get '/learn/:category', to: 'learn#index', as: 'category_learn'
  resources :practices, only: [:index, :show]
  get '/practices/answers/:id/:answer_id', to: 'practices#answers', as: 'answer_practice'
  get '/practices/respond/:id/:answer_id', to: 'practices#respond', as: 'respond_practice'

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_statistics.haml
.row
  .col-lg-4.col-md-6.col-sm-6.col-xs-12
    .card
      .card-height-indicator
      .card-content
        .card-image
          = image_tag('card_01.png')
          %h3.card-image-headline
            Leyes de tránsito
        .card-body
          %p
            #{current_user.law_correct_answers.size} de #{current_user.law_answers.size}
            preguntas contestadas correctamente. Porcentaje de acierto:
            %strong
              #{current_user.law_success_rate}%
          %p
            Nivel
            %span{ class: "#{current_user.law_success_rate < 50 ? 'text-danger' : ( current_user.law_success_rate < 70 ? 'text-warning' : 'text-success' )}" }
              - case current_user.law_success_rate
              - when 0 .. 50
                Bajo
              - when 50 .. 70
                Intermedio
              - else
                Avanzado
        %footer.card-footer
          = link_to 'Practicar', practices_url(category: 'law'), class: 'btn btn-flat'
          = link_to 'Aprender', category_learn_url('law'), class: 'btn btn-flat btn-warning'
  .col-lg-4.col-md-6.col-sm-6.col-xs-12
    .card
      .card-height-indicator
      .card-content
        .card-image
          = image_tag('card_02.png')
          %h3.card-image-headline
            Infracciones
        .card-body
          %p
            #{current_user.penalty_correct_answers.size} de #{current_user.penalty_answers.size}
            preguntas contestadas correctamente. Porcentaje de acierto:
            %strong
              #{current_user.penalty_success_rate}%
          %p
            Nivel
            %span{ class: "#{current_user.penalty_success_rate < 50 ? 'text-danger' : ( current_user.penalty_success_rate < 70 ? 'text-warning' : 'text-success' )}" }
              - case current_user.penalty_success_rate
              - when 0 .. 50
                Bajo
              - when 50 .. 70
                Intermedio
              - else
                Avanzado
        %footer.card-footer
          = link_to 'Practicar', practices_url(category: 'penalty'), class: 'btn btn-flat'
          = link_to 'Aprender', category_learn_url('penalty'), class: 'btn btn-flat btn-warning'

  .col-lg-4.col-md-6.col-sm-6.col-xs-12
    .card
      .card-height-indicator
      .card-content
        .card-image
          = image_tag('card_03.png')
          %h3.card-image-headline
            Señales de tránsito
        .card-body
          %p
            #{current_user.sign_correct_answers.size} de #{current_user.sign_answers.size}
            preguntas contestadas correctamente. Porcentaje de acierto:
            %strong
              #{current_user.sign_success_rate}%
          %p
            Nivel
            %span{ class: "#{current_user.sign_success_rate < 50 ? 'text-danger' : ( current_user.sign_success_rate < 70 ? 'text-warning' : 'text-success' )}" }
              - case current_user.sign_success_rate
              - when 0 .. 50
                Bajo
              - when 50 .. 70
                Intermedio
              - else
                Avanzado
        %footer.card-footer
          = link_to 'Practicar', practices_url(category: 'sign'), class: 'btn btn-flat'
          = link_to 'Aprender', category_learn_url('sign'), class: 'btn btn-flat btn-warning'

-#
  %br
  .row
    .col-lg-12
      .card
        .card-height-indicator
        .card-content
          .card-image
            = image_tag('card_04.png')
            %h3.card-image-headline
              Estadísticas
          .card-body
            %p
              Lorem Ipsum is simply dummy text of the printing and typesetting industry.
          %footer.card-footer
            %button.btn.btn-flat
              Compartir
            %button.btn.btn-flat.btn-warning
              Aprender mas


-#
  :javascript
    $(function(){
    // Load the Visualization API and the corechart package.
    google.charts.load('current', {'packages':['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {

    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Topping');
    data.addColumn('number', 'Slices');
    data.addRows([
    ['Mushrooms', 3],
    ['Onions', 1],
    ['Olives', 1],
    ['Zucchini', 1],
    ['Pepperoni', 2]
    ]);

    // Set chart options
    var options = {'title':'How Much Pizza I Ate Last Night',
    'width':400,
    'height':300};

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
    chart.draw(data, options);
    }
    });

app/views/home/index.haml
%h1.center
  = image_tag(current_user.image.url, class: 'img-circle')
  = "¡Bienvenido #{current_user.name}!"

.row
  .col-xs-12
    - if current_user.need_training?
      Antes de iniciar, necesitamos medir el nivel en el que estas, por favor de clic en el botón medir nivel:
      %br
      %br
      = "#{current_user.percent_training}%"
      .progress
        .progress-bar{role: 'progressbar', aria: {valuenow: current_user.percent_training, valuemin: 0, valuemax: 100}, style: "width: #{current_user.percent_training == 0 ? "2" : current_user.percent_training}%;", class: "#{current_user.percent_training < 20 ? "progress-bar-danger" : ( current_user.percent_training < 70 ? "progress-bar-warning" : "progress-bar-success" )}"}
      = link_to trainings_url, class: 'btn btn-primary btn-raised' do
        Medir nivel
    - else
      = render 'statistics'