config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resources :trainings, only: [:index, :show]
  get '/trainings/answers/:id/:answer_id', to: 'trainings#answers', as: 'answer_training'
  resources :learn, only: [:index]
  get '/learn/:category', to: 'learn#index', as: 'category_learn'
  resources :practices, only: [:index, :show]
  get '/practices/answers/:id/:answer_id', to: 'practices#answers', as: 'answer_practice'
  get '/practices/respond/:id/:answer_id', to: 'practices#respond', as: 'respond_practice'

  root 'home#index'

end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :authenticate_user!

  def index
    # Find a valid question for user and redirect to show
    if params[:category]
      question = Question.where(category: params[:category]).random
      redirect_to practice_url(question, category: params[:category]) and return
    else
      question = Question.for_user(current_user).random
      redirect_to practice_url(question) and return
    end
  end

  def show
    add_breadcrumb "Dashboard", root_path
    add_breadcrumb "Practicar", practices_url
    if params[:category]
      add_breadcrumb Question::CATEGORY[params[:category].to_s]
    end
  end

  def respond
    redirect_to root_url, alert: "¡Ups! Lo sentimos, la pregunta que intento contestar no existe." and return unless question
    @answer = current_user.user_questions.new
    @answer.question_id = question.id
    @answer.answer = params[:answer_id]
    @answer.level = question.level
    @answer.save
    redirect_to answer_practice_url(question, params[:answer_id], category: params[:category]) and return
  end

  def answers
    redirect_to root_url, alert: "¡Ups! Lo sentimos, la pregunta que intento contestar no existe." and return unless question
    @answer = current_user.user_questions.limit(1).order(id: :desc).where(question_id: question.id).first
    add_breadcrumb "Dashboard", root_path
    add_breadcrumb "Practicar", practices_url
    if params[:category]
      add_breadcrumb Question::CATEGORY[params[:category].to_s]
    end
  end

  def question
    @question ||= Question.find(params[:id])
  end
  helper_method :question

end

app/views/practices/answers.haml
%ul.breadcrumb
  = render_breadcrumbs tag: :li, separator: ''
.panel{class: "panel-#{@answer.correct? ? "success" : "danger"}"}
  .panel-heading
    %strong
      %span.glyphicon{aria: {hidden: true}, class: "#{question.glyphicon}"}
      = question.category_s
  .panel-body
    = question.question
    - if question.image.present?
      .row
        .col-sm-offset-5.col-sm-2.col-xs-6.col-xs-offset-3
          = image_tag(question.image.url(:thumb), class: 'img-responsive img-thumbnail')
  .list-group
    - ( 1 .. 4).each do |n|
      - if question["answer_#{n}"].present?
        .list-group-item{class: @answer.correct_answer == n ? 'success' : ( @answer.answer == n ? 'danger' : nil) }
          .row-action-primary
            = link_to 'javascript:void(0)' do
              %i.material-icons
                - if @answer.correct_answer == n
                  check_circle
                - elsif @answer.answer == n
                  error
                - else
                  - case n
                  - when 1
                    looks_one
                  - when 2
                    looks_two
                  - when 3
                    looks_3
                  - else
                    looks_4
          .row-content
            .list-group-item-text
              = link_to 'javascript:void(0)', class: 'btn btn-no-upper' do
                = question["answer_#{n}"]
        - if n < 4
          .list-group-separator
    %div.text-right
      = link_to "Siguiente pregunta", practices_url(category: params[:category]), class: 'btn'

app/views/practices/show.haml
%ul.breadcrumb
  = render_breadcrumbs tag: :li, separator: ''
.panel.panel-default
  .panel-heading
    %strong
      %span.glyphicon{aria: {hidden: true}, class: "#{question.glyphicon}"}
      = question.category_s
  .panel-body
    = question.question
    - if question.image.present?
      .row
        .col-sm-offset-5.col-sm-2.col-xs-6.col-xs-offset-3
          = image_tag(question.image.url(:thumb), class: 'img-responsive img-thumbnail')
  .list-group
    - ( 1 .. 4).each do |n|
      - if question["answer_#{n}"].present?
        .list-group-item
          .row-action-primary
            = link_to respond_practice_url(question, n, category: params[:category]) do
              %i.material-icons
                - case n
                - when 1
                  looks_one
                - when 2
                  looks_two
                - when 3
                  looks_3
                - else
                  looks_4
          .row-content
            .list-group-item-text
              = link_to respond_practice_url(question, n, category: params[:category]), class: 'btn btn-no-upper' do
                = question["answer_#{n}"]
        - if n < 4
          .list-group-separator